DROP TABLE IF EXISTS `test`.`order`;
CREATE TABLE `order` (
  `ORDER_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `CUSTOMER_NAME` varchar(20) NOT NULL,
  `CUSTOMER_ADDRESS` varchar(50) NOT NULL,
  `DATE` date NOT NULL,
  PRIMARY KEY (`ORDER_ID`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `test`.`product`;
CREATE TABLE `product` (
  `PRODUCT_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) NOT NULL,
  `IMG_LINK` varchar(255) NOT NULL,
  `REFERENCE` int(10) NOT NULL,
  `STOCK_QUANTITY` int(10) NOT NULL,
  `PRICE` double(10) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`) USING BTREE,
  UNIQUE KEY `REFRENCE` (`REFERENCE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `test`.`order_line`;
CREATE TABLE  `order_line` (
  `ORDER_LINE_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ORDER_ID` int(10) unsigned NOT NULL,
  `PRODUCT_ID` int(10) unsigned NOT NULL,
  `QUANTITY` int(10) NOT NULL,
  PRIMARY KEY (`ORDER_LINE_ID`),
  KEY `FK_ORDER_ID` (`ORDER_ID`),
  KEY `FK_PRODUCT_ID` (`PRODUCT_ID`),
  CONSTRAINT `FK_ORDER_ID` FOREIGN KEY (`ORDER_ID`) REFERENCES `order` (`ORDER_ID`),
  CONSTRAINT `FK_PRODUCT_ID` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `product` (`PRODUCT_ID`)
) ENGINE=InnoDB CHARSET=utf8;